import type { Participant } from '../model/schema';

export type ParticipantSeed = Omit<Participant, 'projects'>;

const about =
  'Nunc fringilla dui diam, vel placerat tortor facilisis vitae. Mauris pellentesque eros ut congue condimentum. Nullam venenatis augue id urna cursus, ut euismod mauris accumsan. Nullam eu sollicitudin lorem. Vestibulum imperdiet arcu ac faucibus tristique.';

const achievements =
  'SMF Animation operates as a multi-platform entertainment company that includes animation production, licensing, educational initiatives, and creative development facilities. Content is broadcast and streamed in more than 120 countries, including France, the United Kingdom, Germany, Israel, China, and Indonesia.';

const contact = (name: string, email: string) => ({
  name,
  position: 'Director of International Sales and Projects',
  email,
  photo: null,
});

export const participantsSeed: ParticipantSeed[] = [
  {
    id: 'smf-animation',
    name: 'SMF Animation',
    website: 'https://www.smfanimation.com',
    websiteLabel: 'www.smfanimation.com',
    logo: null,
    origin: 'russian',
    contentTypes: ['animation', 'series'],
    genres: ['adventure', 'comedy', 'fantasy'],
    addressLines: ['21, build.1, Akademika Koroleva str.,', 'Moscow, 127427, Russia'],
    country: 'Russia',
    distributionTerritory: null,
    about,
    achievements,
    contact: contact('Maria Savinykh', 'm.savinykh@smfanimation.com'),
  },
  {
    id: 'av-company',
    name: 'Av Company',
    website: 'https://www.company.com',
    websiteLabel: 'www.company.com',
    logo: null,
    origin: 'russian',
    contentTypes: ['feature-film', 'documentary'],
    genres: ['drama', 'romance', 'adventure'],
    addressLines: ['12, Tverskaya str.,', 'Moscow, 125009, Russia'],
    country: 'Russia',
    distributionTerritory: null,
    about,
    achievements,
    contact: contact('Anna Belova', 'a.belova@company.com'),
  },
  {
    id: 'b-company',
    name: 'B Company',
    website: 'https://www.bcompany.com',
    websiteLabel: 'www.bcompany.com',
    logo: null,
    origin: 'russian',
    contentTypes: ['animation', 'series'],
    genres: ['sci-fi', 'comedy', 'drama'],
    addressLines: ['5, Nevsky prospect,', 'Saint Petersburg, 191186, Russia'],
    country: 'Russia',
    distributionTerritory: null,
    about,
    achievements: null,
    contact: contact('Ivan Petrov', 'i.petrov@bcompany.com'),
  },
  {
    id: 'c-company',
    name: 'C Company',
    website: 'https://www.ccompany.com',
    websiteLabel: 'www.ccompany.com',
    logo: null,
    origin: 'russian',
    contentTypes: ['animation', 'feature-film'],
    genres: ['musical', 'comedy', 'action'],
    addressLines: ['8, Lenina str.,', 'Kazan, 420111, Russia'],
    country: 'Russia',
    distributionTerritory: null,
    about,
    achievements,
    contact: contact('Olga Smirnova', 'o.smirnova@ccompany.com'),
  },
  {
    id: 'toonz-turkey',
    name: 'Toonz Turkey',
    website: 'https://www.foreigncompany.com',
    websiteLabel: 'www.foreigncompany.com',
    logo: null,
    origin: 'international',
    contentTypes: ['animation', 'series'],
    genres: ['comedy', 'adventure', 'fantasy'],
    addressLines: ['8515. Sokak 10', 'Aksaray, 68000, Turkey'],
    country: 'Turkey',
    distributionTerritory: 'EU, Brazil',
    about,
    achievements: null,
    contact: contact('Regina J.B. Buyer', 'regina@toonz.com'),
  },
  {
    id: 'toonz-armenia',
    name: 'Toonz Armenia',
    website: 'https://www.link.com',
    websiteLabel: 'www.link.com',
    logo: null,
    origin: 'international',
    contentTypes: ['feature-film'],
    genres: ['drama'],
    addressLines: ['1, Abovyan str.', 'Yerevan, 0001, Armenia'],
    country: 'Armenia',
    distributionTerritory: 'CIS, Middle East',
    about,
    achievements: null,
    contact: contact('Aram Sargsyan', 'aram@toonz.am'),
  },
  {
    id: 'd-company',
    name: 'D Company',
    website: 'https://www.dcompany.com',
    websiteLabel: 'www.dcompany.com',
    logo: null,
    origin: 'international',
    contentTypes: ['documentary', 'series'],
    genres: ['adventure'],
    addressLines: ['221B Baker Street', 'London, NW1 6XE, United Kingdom'],
    country: 'United Kingdom',
    distributionTerritory: 'Worldwide',
    about,
    achievements: null,
    contact: contact('John Smith', 'john@dcompany.com'),
  },
  {
    id: 'f-company',
    name: 'F Company',
    website: 'https://www.fcompany.com',
    websiteLabel: 'www.fcompany.com',
    logo: null,
    origin: 'international',
    contentTypes: ['animation'],
    genres: ['fantasy', 'musical'],
    addressLines: ['18 Rue de Rivoli', 'Paris, 75004, France'],
    country: 'France',
    distributionTerritory: 'EU',
    about,
    achievements: null,
    contact: contact('Claire Dubois', 'claire@fcompany.com'),
  },
];
